// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaRMUiVElR1CLhQAC6Va1BTxqg0lc78mo',
    appId: '1:956398394373:web:fb2b33aa96a7eeeb33506c',
    messagingSenderId: '956398394373',
    projectId: 'gorev-takip1905',
    authDomain: 'gorev-takip1905.firebaseapp.com',
    storageBucket: 'gorev-takip1905.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5pKKU1VqF0Nogem6dvPzj7XTvY-Z6vT8',
    appId: '1:956398394373:android:609620c9c62de54133506c',
    messagingSenderId: '956398394373',
    projectId: 'gorev-takip1905',
    storageBucket: 'gorev-takip1905.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUDnsX7IUzfRzQkrk8SNkTHJQfRy_6eAI',
    appId: '1:956398394373:ios:756104d51a25dd8a33506c',
    messagingSenderId: '956398394373',
    projectId: 'gorev-takip1905',
    storageBucket: 'gorev-takip1905.firebasestorage.app',
    iosBundleId: 'com.example.gorevTakipUygulamasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUDnsX7IUzfRzQkrk8SNkTHJQfRy_6eAI',
    appId: '1:956398394373:ios:756104d51a25dd8a33506c',
    messagingSenderId: '956398394373',
    projectId: 'gorev-takip1905',
    storageBucket: 'gorev-takip1905.firebasestorage.app',
    iosBundleId: 'com.example.gorevTakipUygulamasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaRMUiVElR1CLhQAC6Va1BTxqg0lc78mo',
    appId: '1:956398394373:web:1bce0e623250552433506c',
    messagingSenderId: '956398394373',
    projectId: 'gorev-takip1905',
    authDomain: 'gorev-takip1905.firebaseapp.com',
    storageBucket: 'gorev-takip1905.firebasestorage.app',
  );
}